### ISSUE TITLE
connection refused for port 8083

### ISSUE THREAD

**Issue by lsluijter** [RattyDAVE/docker-ubuntu-hercules-vm370#1]
How do I get to the Hercules console (with OPERATOR on 009)?

With http://172.17.0.1:8083 I get a ERR_CONNECTION_REFUSED as answer.

x3270 172.17.0.1:3270 gives me a 24x80 VM screen

Loek Sluijter (retired VM Systems programmer @ IBM)

**Comment by RattyDAVE** [comment]
Hi,


At present this is not enabled as default.  (I need to check).


I am thinking of say the 1st 3270 session be the console. Then after
that the user sessions.

How does that sound? If that sounds good then I make the change.


DAVE

**Comment by RattyDAVE** [comment]
Scrap what I just said.. I am looking at the config now and testing.

**Comment by RattyDAVE** [comment]
Now working.. Just re pull the image.

8083 now working - I think I removed it during a debug clear out. 

As for console connection. You can get that by using telnet if you are quick. A the telnet connection will be the default on failures too.
```
telnet xxx.xxx.xxx.xxxx 3270
```
Dave

**Comment by lsluijter** [comment]
I did a STOP, RM and RMI fore the old image, then I pulled the new one:

15IKBM:~$ sudo docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
rattydave/docker-ubuntu-hercules-vm370   latest              d9869e27d254        24 hours ago        357MB
hello-world                              latest              f2a91732366c        2 months ago        1.85kB

But still I get an ERR_CONNECTION_REFUSED when I try http://172.17.0.1:8083

I can logon CMSUSER with X3270.

(I must be doing something wrong. I have no experience with Docker, I understand what hercules should do, I know all about VM)

**Comment by RattyDAVE** [comment]
Sounds like you are doing every correct!

I am just making step by step instructions and doing it myself....

So stand by... should have something sortly...

(also on a side note with docker i love https://portainer.io/ to manage)

Back in a bit.


DAVE

**Comment by RattyDAVE** [comment]
I have to apologise! My fault.

I made a typo in the instructions.

I am just going through a dry run now.

**Comment by RattyDAVE** [comment]
Hi,

I am rebuilt and tested with the following. For ease do the STOP, RM and RMI as before. Then do below.


#I have a number of machine setups a HOST machine that is a server that runs all my containers. And I have a CLIENT machine that I use to access. if you have the one machine and running locally then do all the commands on the same machine.



HOST MACHINE

```
docker run -d --name vm370 \
           -p 3270:3270 -p 8038:8038 \
           rattydave/docker-ubuntu-hercules-vm370:latest
```

Find out your IP ADDRESS

```
ip addr show
```

Look for ETH0 or something you recognise. You are looking for the IP address that your computer conects to the network. Not the internal docker vlans or transit networks. (Hint prob a 192.168.x.x address for home users)


CLIENT MACHINE

xxx.xxx.xxx.xxx is the host machine IP address.

Open Web browser to   http://xxx.xxx.xxx.xxx:8038
You should see a "Hercules System Log"

```
telnet xxx.xxx.xxx.xxx:3270 
```

You should see a response. If you type LOGIN and a USERID you should see a password prompt.

```
x3270 -reconnect -model 2 xxx.xxx.xxx.xxx:3270 &
```

You should see a 3270 screen with a VM370 logo.

**Comment by lsluijter** [comment]
Got it!! 
Hercules console is on port 8038, not 8083. IP address is in my case "localhost" or 127.0.0.1 or 192.168.x.x.   http://localhost:8038/ works for me.

The Telnet and X3270  go to IP address 172.17.0.1

Thanks!

**Comment by RattyDAVE** [comment]
No problem...  All my fault. I am going to change the start up process later. So it uses screen then be able to debug better. I already have it working on the TSS container.On 16 Feb 2018 10:18 am, Loek Sluijter <notifications@github.com> wrote:Got it!!
Hercules console is on port 8038, not 8083. IP address is in my case "localhost" or 127.0.0.1 or 192.168.x.x.   http://localhost:8038/ works for me.
The Telnet and X3270  go to IP address 172.17.0.1
Thanks!
