### ISSUE TITLE
COBOL program

### ISSUE THREAD

**Issue by sukonin** [RattyDAVE/docker-ubuntu-hercules-vm370#2]
Hi! Is it possible to run COBOL application on this emulator?

**Comment by RattyDAVE** [comment]
YES! Very much so!

http://www.bitsavers.org/pdf/ibm/370/CMS/cobol/SC28-6469-5_IBM_CMS_Users_Guide_for_COBOL_Aug83.pdf

**Comment by sukonin** [comment]
Thank you for quick response! this information is very useful.

**Comment by RattyDAVE** [comment]
Just to add I loaded it up and checked for myself. 

once logged in the commands I used was....

dir cobol exec *

cobol

You can see these on the screenshot.


![image](https://user-images.githubusercontent.com/9049822/45320073-88578300-b539-11e8-8c0e-56196cc09ec0.png)

**Comment by LionelBergen** [comment]
> 
> 
> YES! Very much so!
> 
> http://www.bitsavers.org/pdf/ibm/370/CMS/cobol/SC28-6469-5_IBM_CMS_Users_Guide_for_COBOL_Aug83.pdf

Is there another link? That website is down

**Comment by RattyDAVE** [comment]
Yesterday bitsavers was down.

I have just tried today and working fine.
