### ISSUE TITLE
IPL not working?

### ISSUE THREAD

**Issue by adesutherland** [RattyDAVE/docker-ubuntu-hercules-vm370#3]
Hello!

I have tried this on both the beta and latest (pulled today).

Web Console and port 3270 don't come up ...

So when I connect to the screen herc I see:

```
> HHCTT001W Timer thread set priority -20 failed: Permission denied                                                                                                                             +HHCTT002I Timer thread started: tid=7F65B25C7700, pid=9, priority=8
> HHCCP003I CPU0000 architecture mode S/370
> HHCPN001I Control panel thread started: tid=7F65BAA25740, pid=9
> HHCPN008I Script file processing started using file "hercules.rc"
> HHCAO001I Hercules Automatic Operator thread started;
>           tid=7F65B22C4700, pri=8, pid=9
> * Hercules runs the commands in this file upon startup.
> * IPL VM/370, which resides on device 141.
> HHCPN011I Pausing SCRIPT file processing for 2 seconds...
> HHCPN012I Resuming SCRIPT file processing...
> ipl 141
> * Enable any attached devices.
> HHCPN011I Pausing SCRIPT file processing for 4 seconds...
> HHCCD001I Readahead thread 1 started: tid=7F65B20C2700, pid=9
> HHCCD001I Readahead thread 2 started: tid=7F65B1FC1700, pid=9
> HHCCD002I Writer thread 1 started: tid=7F65B1BBD700, pid=9
> HHCCD002I Writer thread 2 started: tid=7F65B1CBE700, pid=9
> HHCPN012I Resuming SCRIPT file processing...
> /enable all
> HHCPN139E Command "/enable" not found; enter '?' for list.
> 

```
When I manually type

> .enable all

just for a laugh (!), I get
 
`HHCCP037E SCP not receiving commands`

Anyway - there are no messages indicating that the IPL has worked?!

I have not changed anything - I just did a pull ...

Thoughts?

Adrian

**Comment by RattyDAVE** [comment]
Hi there.

Let me check!

Back in a bit!

**Comment by RattyDAVE** [comment]
Do you get this when you telnet in?

![image](https://user-images.githubusercontent.com/9049822/71285039-1dac0e80-235c-11ea-99f1-5a28e32e41ea.png)

**Comment by RattyDAVE** [comment]
Then followed by....

![image](https://user-images.githubusercontent.com/9049822/71285405-fa359380-235c-11ea-809e-d6506ebcba67.png)

**Comment by RattyDAVE** [comment]
I was able to login with 

```
LOGIN CMSUSER
CMSUSER
```

Then I am in. I can then issue `HELP CMSCMDS`

You do not need to IPL via the console. That is already scripted in!

**Comment by adesutherland** [comment]
I will need to check in the morning :-)

I didn't have telnet (it's all ssh!) ... it may very well be that VM is
waiting on the console to appear via telnet before IPLing?

Thanks!!

Adrian

**Comment by adesutherland** [comment]
Ps ... Do you mind if I do some changes to you docker files. I want to add
novnc and x3270 so people don't need to worry about about ask that 3270
stuff!

Pull request?

A

**Comment by RattyDAVE** [comment]
In answer to the NOVNC

- I dont think this is in scope in this tag. 
- I do like the idea! So I am thinking ...... have another tag with novnc and x3270.

So feel free to do a pull. And take from there.

Either way this is open source ... feel free to make fork / make changes..

BTW In answer to the question. You dont need to telnet before. Just connect via 3270.

**Comment by RattyDAVE** [comment]
Just checked. If I run the following I get the VM370 screen. No other commands.  

```
$docker run -dit --name vm370 -p 3270:3270 -p 8038:8038 rattydave/docker-ubuntu-hercules-vm370:latest
1a4ce8f4e7f4262442ed87e18dc32375504307e8ceb6ca5061fef3471a5dd269
$ x3270 127.0.0.1 3270
```

**Comment by adesutherland** [comment]
All works

The issue was that I was using docker.host rather than 127.0.0.1 - my bad!

Thanks - will play further ...

**Comment by RattyDAVE** [comment]
No problem!...
